### ISSUE TITLE
Missing `strip-ansi` dependency

### ISSUE THREAD

**Issue by cdfa** [0x80/yurnalist#11]
Hi, I tried installing this package with [pnpm](https://pnpm.js.org/), but running the activity example fails because of a missing `strip-ansi` dependency.

Steps to reproduce:
```
$ git clone https://github.com/0x80/yurnalist.git
$ pnpm i
$ npm run build
$ node examples/activity.js
module.js:550
throw err;
^
Error: Cannot find module 'strip-ansi'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/cdfa/Projects/yurnalist/dist/reporters/console/console-reporter.js:63:19)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
```

**Comment by 0x80** [comment]
Thanks for reporting! I've released 1.0.5 with the fix.
